preprocess:
  input_path: data/raw/heart.csv
  output_dir: data/processed
  target_column: "target" 
  test_size: 0.2
  random_state: 42

train:
  model_dir: models
  model_params:
    n_estimators: 100
    max_depth: 10

tune:
  n_estimators: [50, 100, 200, 300]
  max_depth: [5, 10, 15, 20]

mlflow:
  tracking_uri: "https://dagshub.com/karim-raouf/lab-3-mlops.mlflow"  # Will be updated to DagsHub URI
  experiment_name: "lab-3-mlops"